2021-06-07 16:20:37 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "CREATE DATABASE[*] USERLIKE"; 期待されるステートメント "OR, FORCE, VIEW, ALIAS, SEQUENCE, USER, TRIGGER, ROLE, SCHEMA, CONSTANT, DOMAIN, TYPE, DATATYPE, AGGREGATE, LINKED, MEMORY, CACHED, LOCAL, GLOBAL, TEMP, TEMPORARY, TABLE, SYNONYM, PRIMARY, UNIQUE, HASH, SPATIAL, INDEX"
Syntax error in SQL statement "CREATE DATABASE[*] USERLIKE"; expected "OR, FORCE, VIEW, ALIAS, SEQUENCE, USER, TRIGGER, ROLE, SCHEMA, CONSTANT, DOMAIN, TYPE, DATATYPE, AGGREGATE, LINKED, MEMORY, CACHED, LOCAL, GLOBAL, TEMP, TEMPORARY, TABLE, SYNONYM, PRIMARY, UNIQUE, HASH, SPATIAL, INDEX"; SQL statement:
create database UserLike [42001-200]
2021-06-07 17:41:12 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: 不明なデータ型: 
Unknown data type: ; SQL statement:
alter table t_id add c_name [50004-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:5971)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:5697)
	at org.h2.command.Parser.parseTableColumnDefinition(Parser.java:8442)
	at org.h2.command.Parser.parseAlterTableAddColumn(Parser.java:8133)
	at org.h2.command.Parser.parseAlterTable(Parser.java:7690)
	at org.h2.command.Parser.parseAlter(Parser.java:6983)
	at org.h2.command.Parser.parsePrepared(Parser.java:887)
	at org.h2.command.Parser.parse(Parser.java:843)
	at org.h2.command.Parser.parse(Parser.java:815)
	at org.h2.command.Parser.prepareCommand(Parser.java:738)
	at org.h2.engine.Session.prepareLocal(Session.java:657)
	at org.h2.engine.Session.prepareCommand(Session.java:595)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:212)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:201)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1459)
	at org.h2.server.web.WebApp.query(WebApp.java:1116)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1078)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1065)
	at org.h2.server.web.WebThread.process(WebThread.java:178)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021-06-08 14:00:01 jdbc[5]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列番号が一致しません
Column count does not match; SQL statement:
insert into t_idpw 
values('melon','daisuki') [21002-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:453)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.command.dml.Insert.prepare(Insert.java:319)
	at org.h2.command.Parser.prepareCommand(Parser.java:744)
	at org.h2.engine.Session.prepareLocal(Session.java:657)
	at org.h2.engine.Session.prepareCommand(Session.java:595)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:212)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:201)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1459)
	at org.h2.server.web.WebApp.query(WebApp.java:1116)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1078)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1065)
	at org.h2.server.web.WebThread.process(WebThread.java:178)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021-06-08 14:49:41 jdbc[6]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列名 "S_ID" があいまいです
Ambiguous column name "S_ID"; SQL statement:
select s_id from profile right join s_idpw 
on profile.s_id = s_idpw.s_id [90059-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:576)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.mapColumn(ExpressionColumn.java:129)
	at org.h2.expression.ExpressionColumn.mapColumns(ExpressionColumn.java:107)
	at org.h2.command.dml.Select.mapColumns(Select.java:1600)
	at org.h2.command.dml.Select.init(Select.java:1125)
	at org.h2.command.Parser.parseQuery(Parser.java:2627)
	at org.h2.command.Parser.parsePrepared(Parser.java:868)
	at org.h2.command.Parser.parse(Parser.java:843)
	at org.h2.command.Parser.parse(Parser.java:815)
	at org.h2.command.Parser.prepareCommand(Parser.java:738)
	at org.h2.engine.Session.prepareLocal(Session.java:657)
	at org.h2.engine.Session.prepareCommand(Session.java:595)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:212)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:201)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1459)
	at org.h2.server.web.WebApp.query(WebApp.java:1116)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1078)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1065)
	at org.h2.server.web.WebThread.process(WebThread.java:178)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021-06-08 14:51:49 jdbc[6]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列名 "S_ID" があいまいです
Ambiguous column name "S_ID"; SQL statement:
select s_id from s_idpw right join profile  
on s_idpw.s_id = profile.s_id [90059-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:576)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.mapColumn(ExpressionColumn.java:129)
	at org.h2.expression.ExpressionColumn.mapColumns(ExpressionColumn.java:107)
	at org.h2.command.dml.Select.mapColumns(Select.java:1600)
	at org.h2.command.dml.Select.init(Select.java:1125)
	at org.h2.command.Parser.parseQuery(Parser.java:2627)
	at org.h2.command.Parser.parsePrepared(Parser.java:868)
	at org.h2.command.Parser.parse(Parser.java:843)
	at org.h2.command.Parser.parse(Parser.java:815)
	at org.h2.command.Parser.prepareCommand(Parser.java:738)
	at org.h2.engine.Session.prepareLocal(Session.java:657)
	at org.h2.engine.Session.prepareCommand(Session.java:595)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:212)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:201)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1459)
	at org.h2.server.web.WebApp.query(WebApp.java:1116)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1078)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1065)
	at org.h2.server.web.WebThread.process(WebThread.java:178)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021-06-08 15:17:13 jdbc[6]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列名 "S_ID" があいまいです
Ambiguous column name "S_ID"; SQL statement:
select s_id,s_id from s_idpw right join profile  
on s_idpw.s_id = profile.s_id [90059-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:576)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.mapColumn(ExpressionColumn.java:129)
	at org.h2.expression.ExpressionColumn.mapColumns(ExpressionColumn.java:107)
	at org.h2.command.dml.Select.mapColumns(Select.java:1600)
	at org.h2.command.dml.Select.init(Select.java:1125)
	at org.h2.command.Parser.parseQuery(Parser.java:2627)
	at org.h2.command.Parser.parsePrepared(Parser.java:868)
	at org.h2.command.Parser.parse(Parser.java:843)
	at org.h2.command.Parser.parse(Parser.java:815)
	at org.h2.command.Parser.prepareCommand(Parser.java:738)
	at org.h2.engine.Session.prepareLocal(Session.java:657)
	at org.h2.engine.Session.prepareCommand(Session.java:595)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:212)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:201)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1459)
	at org.h2.server.web.WebApp.query(WebApp.java:1116)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1078)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1065)
	at org.h2.server.web.WebThread.process(WebThread.java:178)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021-06-08 15:47:20 jdbc[6]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: 列名 "S_ID" が重複しています
Duplicate column name "S_ID"; SQL statement:
insert into profile (
s_id,s_id ) select s_id,s_id 
from s_idpw [42121-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:453)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.command.Parser.parseColumnList(Parser.java:1437)
	at org.h2.command.Parser.parseInsertGivenTable(Parser.java:1804)
	at org.h2.command.Parser.parseInsert(Parser.java:1749)
	at org.h2.command.Parser.parsePrepared(Parser.java:954)
	at org.h2.command.Parser.parse(Parser.java:843)
	at org.h2.command.Parser.parse(Parser.java:815)
	at org.h2.command.Parser.prepareCommand(Parser.java:738)
	at org.h2.engine.Session.prepareLocal(Session.java:657)
	at org.h2.engine.Session.prepareCommand(Session.java:595)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:212)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:201)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1459)
	at org.h2.server.web.WebApp.query(WebApp.java:1116)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1078)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1065)
	at org.h2.server.web.WebThread.process(WebThread.java:178)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021-06-08 16:38:16 jdbc[7]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:100)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:187)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:309)
	at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:289)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:785)
	at org.h2.server.web.WebApp.login(WebApp.java:1008)
	at org.h2.server.web.WebApp.process(WebApp.java:223)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:173)
	at org.h2.server.web.WebThread.process(WebThread.java:139)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.base/java.lang.Thread.run(Thread.java:834)

org.h2.message.DbException: アプリケーションにより閉じられていない接続がガベージコレクトされました
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:309)
	at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:289)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:785)
	at org.h2.server.web.WebApp.login(WebApp.java:1008)
	at org.h2.server.web.WebApp.process(WebApp.java:223)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:173)
	at org.h2.server.web.WebThread.process(WebThread.java:139)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: アプリケーションにより閉じられていない接続がガベージコレクトされました
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 16 more
2021-06-08 16:38:16 jdbc[7]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:100)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:187)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:309)
	at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:289)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:785)
	at org.h2.server.web.WebApp.login(WebApp.java:1008)
	at org.h2.server.web.WebApp.process(WebApp.java:223)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:173)
	at org.h2.server.web.WebThread.process(WebThread.java:139)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.base/java.lang.Thread.run(Thread.java:834)

org.h2.message.DbException: アプリケーションにより閉じられていない接続がガベージコレクトされました
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:309)
	at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:289)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:785)
	at org.h2.server.web.WebApp.login(WebApp.java:1008)
	at org.h2.server.web.WebApp.process(WebApp.java:223)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:173)
	at org.h2.server.web.WebThread.process(WebThread.java:139)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: アプリケーションにより閉じられていない接続がガベージコレクトされました
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 16 more
2021-06-08 16:38:16 jdbc[7]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:100)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:187)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:309)
	at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:289)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:785)
	at org.h2.server.web.WebApp.login(WebApp.java:1008)
	at org.h2.server.web.WebApp.process(WebApp.java:223)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:173)
	at org.h2.server.web.WebThread.process(WebThread.java:139)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.base/java.lang.Thread.run(Thread.java:834)

org.h2.message.DbException: アプリケーションにより閉じられていない接続がガベージコレクトされました
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:309)
	at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:289)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:785)
	at org.h2.server.web.WebApp.login(WebApp.java:1008)
	at org.h2.server.web.WebApp.process(WebApp.java:223)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:173)
	at org.h2.server.web.WebThread.process(WebThread.java:139)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: アプリケーションにより閉じられていない接続がガベージコレクトされました
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 16 more
2021-06-08 16:42:23 jdbc[7]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "INSERT INTO PROFILE 

VALUES([*]‘ABCDEF’, ‘かぐや姫’,’NULL’, ‘KAGUYA@ICLOUD.COM’, 

’F’,’B’,’Y’,’姫市立大学’,’神奈川県’, ‘散歩’,’料理’, 

‘YOASOBIの夜にかける’,’コンビニ’,’特になし’,’竹に住んでいたことがあります。’,’30’)"
Syntax error in SQL statement "INSERT INTO PROFILE 

VALUES([*]‘ABCDEF’, ‘かぐや姫’,’NULL’, ‘KAGUYA@ICLOUD.COM’, 

’F’,’B’,’Y’,’姫市立大学’,’神奈川県’, ‘散歩’,’料理’, 

‘YOASOBIの夜にかける’,’コンビニ’,’特になし’,’竹に住んでいたことがあります。’,’30’)"; SQL statement:
Insert into profile 

Values(‘abcdef’, ‘かぐや姫’,’null’, ‘kaguya@icloud.com’, 

’f’,’b’,’Y’,’姫市立大学’,’神奈川県’, ‘散歩’,’料理’, 

‘yoasobiの夜にかける’,’コンビニ’,’特になし’,’竹に住んでいたことがあります。’,’30’) [42000-200]
2021-06-08 16:42:23 jdbc[7]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "insert into profile 

values('room','織姫',null',’orihime.yahoo.co.jp’, 

'm','e','n','月見大学','愛知県','読書','裁縫', 

'thank u, next','なし','なし','努力家といわれます','120'); 

 

insert into profile  

values('tabekko','たべっこどうぶつ',null,'umashika@gmail.com', 

'f','b','N','どうぶつえん大学','愛知県','散歩','擬態すること', 

'サファリパークの歌','パティシエ補助','特になし','サバイバルが得意です。','0[*]');"
Syntax error in SQL statement "insert into profile 

values('room','織姫',null',’orihime.yahoo.co.jp’, 

'm','e','n','月見大学','愛知県','読書','裁縫', 

'thank u, next','なし','なし','努力家といわれます','120'); 

 

insert into profile  

values('tabekko','たべっこどうぶつ',null,'umashika@gmail.com', 

'f','b','N','どうぶつえん大学','愛知県','散歩','擬態すること', 

'サファリパークの歌','パティシエ補助','特になし','サバイバルが得意です。','0[*]');"; SQL statement:
insert into profile 

values('room','織姫',null',’orihime.yahoo.co.jp’, 

'm','e','n','月見大学','愛知県','読書','裁縫', 

'thank u, next','なし','なし','努力家といわれます','120'); 

 

insert into profile  

values('tabekko','たべっこどうぶつ',null,'umashika@gmail.com', 

'f','b','N','どうぶつえん大学','愛知県','散歩','擬態すること', 

'サファリパークの歌','パティシエ補助','特になし','サバイバルが得意です。','0'); [42000-200]
2021-06-08 16:44:21 jdbc[7]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "INSERT INTO PROFILE 

VALUES([*]‘ABCDEF’, ‘かぐや姫’,’NULL’, ‘KAGUYA@ICLOUD.COM’, 

’F’,’B’,’Y’,’姫市立大学’,’神奈川県’, ‘散歩’,’料理’, 

‘YOASOBIの夜にかける’,’コンビニ’,’特になし’,’竹に住んでいたことがあります。’,’30’)"
Syntax error in SQL statement "INSERT INTO PROFILE 

VALUES([*]‘ABCDEF’, ‘かぐや姫’,’NULL’, ‘KAGUYA@ICLOUD.COM’, 

’F’,’B’,’Y’,’姫市立大学’,’神奈川県’, ‘散歩’,’料理’, 

‘YOASOBIの夜にかける’,’コンビニ’,’特になし’,’竹に住んでいたことがあります。’,’30’)"; SQL statement:
Insert into profile 

Values(‘abcdef’, ‘かぐや姫’,’null’, ‘kaguya@icloud.com’, 

’f’,’b’,’Y’,’姫市立大学’,’神奈川県’, ‘散歩’,’料理’, 

‘yoasobiの夜にかける’,’コンビニ’,’特になし’,’竹に住んでいたことがあります。’,’30’) [42000-200]
2021-06-08 16:45:02 jdbc[7]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "INSERT INTO PROFILE 
VALUES([*]‘ABCDEF’, ‘かぐや姫’,’NULL’, ‘KAGUYA@ICLOUD.COM’, 
’F’,’B’,’Y’,’姫市立大学’,’神奈川県’, ‘散歩’,’料理’, 
‘YOASOBIの夜にかける’,’コンビニ’,’特になし’,’竹に住んでいたことがあります。’,’30’)"
Syntax error in SQL statement "INSERT INTO PROFILE 
VALUES([*]‘ABCDEF’, ‘かぐや姫’,’NULL’, ‘KAGUYA@ICLOUD.COM’, 
’F’,’B’,’Y’,’姫市立大学’,’神奈川県’, ‘散歩’,’料理’, 
‘YOASOBIの夜にかける’,’コンビニ’,’特になし’,’竹に住んでいたことがあります。’,’30’)"; SQL statement:
Insert into profile 
Values(‘abcdef’, ‘かぐや姫’,’null’, ‘kaguya@icloud.com’, 
’f’,’b’,’Y’,’姫市立大学’,’神奈川県’, ‘散歩’,’料理’, 
‘yoasobiの夜にかける’,’コンビニ’,’特になし’,’竹に住んでいたことがあります。’,’30’) [42000-200]
2021-06-08 16:46:08 jdbc[7]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "insert into profile 

values('room','織姫',null',’orihime.yahoo.co.jp’, 

'm','e','n','月見大学','愛知県','読書','裁縫', 

'thank u, next','なし','なし','努力家といわれます','120[*]');"
Syntax error in SQL statement "insert into profile 

values('room','織姫',null',’orihime.yahoo.co.jp’, 

'm','e','n','月見大学','愛知県','読書','裁縫', 

'thank u, next','なし','なし','努力家といわれます','120[*]');"; SQL statement:
insert into profile 

values('room','織姫',null',’orihime.yahoo.co.jp’, 

'm','e','n','月見大学','愛知県','読書','裁縫', 

'thank u, next','なし','なし','努力家といわれます','120'); [42000-200]
2021-06-08 16:50:12 jdbc[7]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "insert into profile 
values('room','織姫',null',’orihime.yahoo.co.jp’, 
'm','e','n','月見大学','愛知県','読書','裁縫', 
'thank u, next','なし','なし','努力家といわれます','120[*]');"
Syntax error in SQL statement "insert into profile 
values('room','織姫',null',’orihime.yahoo.co.jp’, 
'm','e','n','月見大学','愛知県','読書','裁縫', 
'thank u, next','なし','なし','努力家といわれます','120[*]');"; SQL statement:
insert into profile 
values('room','織姫',null',’orihime.yahoo.co.jp’, 
'm','e','n','月見大学','愛知県','読書','裁縫', 
'thank u, next','なし','なし','努力家といわれます','120'); [42000-200]
2021-06-08 16:50:12 jdbc[7]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "insert into profile 
values('room','織姫',null',’orihime.yahoo.co.jp’, 
'm','e','n','月見大学','愛知県','読書','裁縫', 
'thank u, next','なし','なし','努力家といわれます','120[*]');"
Syntax error in SQL statement "insert into profile 
values('room','織姫',null',’orihime.yahoo.co.jp’, 
'm','e','n','月見大学','愛知県','読書','裁縫', 
'thank u, next','なし','なし','努力家といわれます','120[*]');"; SQL statement:
insert into profile 
values('room','織姫',null',’orihime.yahoo.co.jp’, 
'm','e','n','月見大学','愛知県','読書','裁縫', 
'thank u, next','なし','なし','努力家といわれます','120'); [42000-200]
2021-06-08 16:55:21 jdbc[7]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "INSERT INTO PROFILE 
VALUES('room','織姫',NULL',’orihime.yahoo.co.jp’, 
'[*]M','E','N','月見大学','愛知県','読書','裁縫', 
'THANK U,'next','なし','なし','努力家といわれます','120')"; 期待されるステートメント "[, ::, AT, FORMAT, *, /, %, +, -, ||, ~, !~, NOT, LIKE, ILIKE, REGEXP, IS, IN, BETWEEN, AND, OR, ,, )"
Syntax error in SQL statement "INSERT INTO PROFILE 
VALUES('room','織姫',NULL',’orihime.yahoo.co.jp’, 
'[*]M','E','N','月見大学','愛知県','読書','裁縫', 
'THANK U,'next','なし','なし','努力家といわれます','120')"; expected "[, ::, AT, FORMAT, *, /, %, +, -, ||, ~, !~, NOT, LIKE, ILIKE, REGEXP, IS, IN, BETWEEN, AND, OR, ,, )"; SQL statement:
insert into profile 
values('room','織姫',null',’orihime.yahoo.co.jp’, 
'm','e','n','月見大学','愛知県','読書','裁縫', 
'thank u,'next','なし','なし','努力家といわれます','120') [42001-200]
2021-06-08 17:09:25 jdbc[7]: exception
org.h2.jdbc.JdbcSQLDataException: 16進文字列に不正な文字が含まれています: "null"
Hexadecimal string contains non-hex character: "null"; SQL statement:
insert into profile 
values ('room','織姫','null','orihime.yahoo.co.jp',
'm','e','n','月見大学','愛知県','読書','裁縫',
'thank u','next','無し','努力家','120') [90004-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:590)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.util.StringUtils.convertHexToBytes(StringUtils.java:1053)
	at org.h2.value.Value.convertToBlob(Value.java:1300)
	at org.h2.value.Value.convertTo(Value.java:838)
	at org.h2.value.Value.convertTo(Value.java:772)
	at org.h2.value.TypeInfo.cast(TypeInfo.java:515)
	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:378)
	at org.h2.table.Table.validateConvertUpdateSequence(Table.java:845)
	at org.h2.command.dml.Insert.insertRows(Insert.java:187)
	at org.h2.command.dml.Insert.update(Insert.java:151)
	at org.h2.command.CommandContainer.update(CommandContainer.java:198)
	at org.h2.command.Command.executeUpdate(Command.java:251)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:228)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:201)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1459)
	at org.h2.server.web.WebApp.query(WebApp.java:1116)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1078)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1065)
	at org.h2.server.web.WebThread.process(WebThread.java:178)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021-06-08 17:43:30 jdbc[9]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "INSERT INTO PROFILE 

VALUES([*]‘ABCDEF’, ‘かぐや姫’,NULL, ‘KAGUYA@ICLOUD.COM’, 

’F’,’B’,’Y’,’姫市立大学’,’神奈川県’, ‘散歩’,’料理’, 

‘YOASOBIの夜にかける’,’コンビニ’,’特になし’,’竹に住んでいたことがあります。’,’30’)"
Syntax error in SQL statement "INSERT INTO PROFILE 

VALUES([*]‘ABCDEF’, ‘かぐや姫’,NULL, ‘KAGUYA@ICLOUD.COM’, 

’F’,’B’,’Y’,’姫市立大学’,’神奈川県’, ‘散歩’,’料理’, 

‘YOASOBIの夜にかける’,’コンビニ’,’特になし’,’竹に住んでいたことがあります。’,’30’)"; SQL statement:
Insert into profile 

Values(‘abcdef’, ‘かぐや姫’,null, ‘kaguya@icloud.com’, 

’f’,’b’,’Y’,’姫市立大学’,’神奈川県’, ‘散歩’,’料理’, 

‘yoasobiの夜にかける’,’コンビニ’,’特になし’,’竹に住んでいたことがあります。’,’30’) [42000-200]
2021-06-08 17:46:53 jdbc[9]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "INSERT INTO PROFILE 

VALUES([*]‘ABCDEF’, ‘かぐや姫’,NULL, ‘KAGUYA@ICLOUD.COM’, 

’F’,’B’,’Y’,’姫市立大学’,’神奈川県’, ‘散歩’,’料理’, 

‘YOASOBIの夜にかける’,’コンビニ’,’特になし’,’竹に住んでいたことがあります。’,’30’)"
Syntax error in SQL statement "INSERT INTO PROFILE 

VALUES([*]‘ABCDEF’, ‘かぐや姫’,NULL, ‘KAGUYA@ICLOUD.COM’, 

’F’,’B’,’Y’,’姫市立大学’,’神奈川県’, ‘散歩’,’料理’, 

‘YOASOBIの夜にかける’,’コンビニ’,’特になし’,’竹に住んでいたことがあります。’,’30’)"; SQL statement:
Insert into profile 

Values(‘abcdef’, ‘かぐや姫’,null, ‘kaguya@icloud.com’, 

’f’,’b’,’Y’,’姫市立大学’,’神奈川県’, ‘散歩’,’料理’, 

‘yoasobiの夜にかける’,’コンビニ’,’特になし’,’竹に住んでいたことがあります。’,’30’) [42000-200]
2021-06-08 18:29:49 jdbc[10]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: SQLステートメントに文法エラーがあります "INSERT INTO PROFILE 
VALUES('abcdef','かぐや姫',NULL,'kaguya@icloud.com',
'f','b','Y','姫市立大学','神奈川県','散歩',[*]’料理', 
'YOASOBIの夜にかける','コンビニ',’特になし','竹に住んでいたことがあります。','30')"
Syntax error in SQL statement "INSERT INTO PROFILE 
VALUES('abcdef','かぐや姫',NULL,'kaguya@icloud.com',
'f','b','Y','姫市立大学','神奈川県','散歩',[*]’料理', 
'YOASOBIの夜にかける','コンビニ',’特になし','竹に住んでいたことがあります。','30')"; SQL statement:
Insert into profile 
Values('abcdef','かぐや姫',null,'kaguya@icloud.com',
'f','b','Y','姫市立大学','神奈川県','散歩',’料理', 
'yoasobiの夜にかける','コンビニ',’特になし','竹に住んでいたことがあります。','30') [42000-200]
2021-06-08 22:27:52 jdbc[11]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:100)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:187)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:309)
	at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:289)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:785)
	at org.h2.server.web.WebApp.login(WebApp.java:1008)
	at org.h2.server.web.WebApp.process(WebApp.java:223)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:173)
	at org.h2.server.web.WebThread.process(WebThread.java:139)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.base/java.lang.Thread.run(Thread.java:834)

org.h2.message.DbException: アプリケーションにより閉じられていない接続がガベージコレクトされました
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:309)
	at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:289)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:785)
	at org.h2.server.web.WebApp.login(WebApp.java:1008)
	at org.h2.server.web.WebApp.process(WebApp.java:223)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:173)
	at org.h2.server.web.WebThread.process(WebThread.java:139)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: アプリケーションにより閉じられていない接続がガベージコレクトされました
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 16 more
2021-06-08 22:27:52 jdbc[11]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:100)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:187)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:309)
	at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:289)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:785)
	at org.h2.server.web.WebApp.login(WebApp.java:1008)
	at org.h2.server.web.WebApp.process(WebApp.java:223)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:173)
	at org.h2.server.web.WebThread.process(WebThread.java:139)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.base/java.lang.Thread.run(Thread.java:834)

org.h2.message.DbException: アプリケーションにより閉じられていない接続がガベージコレクトされました
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:309)
	at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:289)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:785)
	at org.h2.server.web.WebApp.login(WebApp.java:1008)
	at org.h2.server.web.WebApp.process(WebApp.java:223)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:173)
	at org.h2.server.web.WebThread.process(WebThread.java:139)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: アプリケーションにより閉じられていない接続がガベージコレクトされました
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 16 more
2021-06-08 22:27:52 jdbc[11]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:100)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:187)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:309)
	at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:289)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:785)
	at org.h2.server.web.WebApp.login(WebApp.java:1008)
	at org.h2.server.web.WebApp.process(WebApp.java:223)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:173)
	at org.h2.server.web.WebThread.process(WebThread.java:139)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.base/java.lang.Thread.run(Thread.java:834)

org.h2.message.DbException: アプリケーションにより閉じられていない接続がガベージコレクトされました
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:309)
	at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:289)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:785)
	at org.h2.server.web.WebApp.login(WebApp.java:1008)
	at org.h2.server.web.WebApp.process(WebApp.java:223)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:173)
	at org.h2.server.web.WebThread.process(WebThread.java:139)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: アプリケーションにより閉じられていない接続がガベージコレクトされました
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 16 more
